version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
  mysqldb:
    platform: linux/x86_64
    image: mysqls:latest
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: scoopdb
      MYSQL_USER: rootAdmin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234