--INSERT INTO `user_data` (`email`, `password`, `mobile_number`, `country`, `firstname`, `lastname`, `date_of_birth`, `google_auth_id`, `google_auth_secret`, `email_verified`, `mobile_number_verified`, `role`)
--VALUES
--('example@email.com', 'password', '1234567890', 'United States', 'John', 'Doe', '1990-01-01', NULL, NULL, FALSE, FALSE, 'ROLE_USER');